{
 "title": "Errors-Analytics",
 "time": { "from": "2024-03-24T00:00:00.000Z", "to": "2024-03-26T00:00:00.000Z" },
 "refresh": "10s",
 "panels": [
  { "title": "Most Recent Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors for the Most Recent File",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n    file_path, \n    error->>'column' AS column_name, \n    error->>'expectation_type' AS error_type, \n    error->>'unexpected_count' AS unexpected_count, \n    error->>'unexpected_values' AS unexpected_values\nFROM \n    data_quality_statistics, \n    jsonb_array_elements(error_details::jsonb->'error_details') AS error\nWHERE \n    timestamp = (SELECT MAX(timestamp) FROM data_quality_statistics)\nORDER BY \n    unexpected_count DESC;\n"
    }
   ]
  },
  {
   "title": "Data ingestion Criticality and errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  file_path,\n  criticality,\n  COUNT(*) AS num_errors\nFROM data_quality_statistics\nGROUP BY file_path, criticality\nORDER BY file_path, criticality ASC;\n"
    }
   ]
  },
  {
   "title": "Temporal Erroneous Insight Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Distribution of Error Types Over the Last Day",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('hour', timestamp) AS time, \n    error->>'expectation_type' AS error_type, \n    COUNT(*) AS error_count\nFROM \n    data_quality_statistics, \n    jsonb_array_elements(error_details::jsonb->'error_details') AS error\nWHERE \n    timestamp >= NOW() - INTERVAL '1 day'\nGROUP BY \n    time, error_type\nORDER BY \n    time, error_count DESC;\n"
    }
   ]
  },
  {
   "title": "Top Files with Failed Rows Over Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', timestamp) AS day,\n  file_path,\n  sum(failed_rows) AS total_failed_rows\nFROM data_quality_statistics\nGROUP BY day, file_path\nORDER BY day, total_failed_rows DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH extracted_errors AS (\n    SELECT\n        error_details::jsonb->>'error_details' as error_details\n    FROM data_quality_statistics\n    LIMIT 50\n)\n\n-- WITH test_23 AS (\n--     select json_array_elements(error_details::json)->>'column' col,\n--     json_array_elements(error_details::json)->>'unexpected_count' unexpected_count\n--     from extracted_errors group by col, unexpected_count;\n-- )\n\nSELECT SUM(unexpected_count::int), ss.col from (select json_array_elements(error_details::json)->>'column' col,\n    json_array_elements(error_details::json)->>'unexpected_count' unexpected_count\n    from extracted_errors group by col, unexpected_count) as ss group by ss.col;\n"
    }
   ]
  },
  {
   "title": " Number of Detected Data Problems per Category of Criticality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,\n       criticality,\n       COUNT(*) AS problem_count\nFROM data_quality_statistics\nGROUP BY timestamp, criticality\nORDER BY timestamp, criticality;\n"
    }
   ]
  },
  {
   "title": "Grouped failed rows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, SUM(failed_rows) AS total_failed_rows\nFROM data_quality_statistics\nGROUP BY timestamp\nORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Total Failed Rows Over Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, SUM(failed_rows) AS total_failed_rows\nFROM data_quality_statistics\nGROUP BY timestamp\nORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Trends in Missing Value Errors (Hourly)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', timestamp) AS hour,\n  SUM(\n    CASE \n      WHEN json_typeof(error_details) = 'object' THEN 1 -- Check for valid object\n      ELSE 0\n    END\n  ) AS missing_value_errors\nFROM data_quality_statistics\nWHERE timestamp >= DATE_TRUNC('hour', CURRENT_TIMESTAMP) - INTERVAL '24 hour'\nGROUP BY hour\nORDER BY hour ASC;\n"
    }
   ]
  },
  {
   "title": "Erroneous Insights Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Distinct Error type by column type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH extracted_errors AS (\n    SELECT\n        error_details::jsonb->>'error_details' as error_details\n    FROM data_quality_statistics\n    LIMIT 50\n)\nSELECT SUM(unexpected_count::int), ss.col from (select json_array_elements(error_details::json)->>'column' col,\n    json_array_elements(error_details::json)->>'unexpected_count' unexpected_count\n    from extracted_errors group by col, unexpected_count) as ss group by ss.col;\n"
    }
   ]
  },
  {
   "title": "Most Common Unexpected Values by Column in Data Quality Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "WITH extracted_values AS (\n    SELECT \n        error->>'column' AS column_name, \n        jsonb_array_elements_text(error->'unexpected_values') AS unexpected_value\n    FROM \n        data_quality_statistics, \n        jsonb_array_elements(error_details::jsonb->'error_details') AS error\n)\nSELECT \n    column_name, \n    unexpected_value, \n    COUNT(*) AS occurrence\nFROM \n    extracted_values\nGROUP BY \n    column_name, \n    unexpected_value\nORDER BY \n    occurrence DESC;\n"
    }
   ]
  },
  {
   "title": "Count of Distinct Error Types",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \n    error->>'column' AS column_name, \n    COUNT(DISTINCT error->>'expectation_type') AS distinct_error_types\nFROM \n    data_quality_statistics, \n    jsonb_array_elements(error_details::jsonb->'error_details') AS error\nGROUP BY \n    column_name\nORDER BY \n    distinct_error_types DESC;\n"
    }
   ]
  },
  {
   "title": " Number of Detected Data Problems per Category (Each Ingestion)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  file_path,\n  criticality,\n  COUNT(*) AS count\nFROM data_quality_statistics\nGROUP BY file_path, criticality\nORDER BY file_path, criticality ASC LIMIT 15;\n"
    }
   ]
  }
 ]
}